### ISSUE TITLE
Allow including one config inside of another

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/angel#133]
*This issue was originally created by @thosakwe here, before being automatically moved: 
https://github.com/angel-dart-archive/configuration/issues/8*
---
Example, `production.yaml`:

```yaml
_include: "./staging.yaml"
_include:
  - "./staging.yaml"
  - "./development.yaml"
```

The YAML contents will be merged; this will occur *before* variables are expanded and placed into `app.configuration`.
