### ISSUE TITLE
build_runner failing with constantValue not defined for FieldElement class

### ISSUE THREAD

**Issue by kevinelliott** [angel-dart/angel#279]
```
Precompiled build_runner:build_runner.
[INFO] Generating build script completed, took 600ms
[INFO] Creating build script snapshot... completed, took 11.6s
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../../../../.pub-cache/hosted/pub.dartlang.org/angel_serialize_generator-2.5.0/lib/angel_serialize_generator.dart:104:55: Error: The getter 'constantValue' isn't defined for the class 'FieldElement'. - 'FieldElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'constantValue'.        var value = type.element.getField(field.name).constantValue;                                                      ^^^^^^^^^^^^^../../../../../.pub-cache/hosted/pub.dartlang.org/angel_serialize_generator-2.5.0/lib/model.dart:88:43: Error: The getter 'type' isn't defined for the class 'ClassElement'. - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.    return !isAssignableToModel(ctx.clazz.type) &&                                          ^^^^../../../../../.pub-cache/hosted/pub.dartlang.org/angel_serialize_generator-2.5.0/lib/model.dart:211:18: Error: The getter 'typeParameters' isn't defined for the class 'InterfaceType'. - 'InterfaceType' is from 'package:analyzer/dart/element/type.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/type.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'typeParameters'.        if (type.typeParameters.length == 1) {                 ^^^^^^^^^^^^^^../../../../../.pub-cache/hosted/pub.dartlang.org/angel_serialize_generator-2.5.0/lib/model.dart:219:18: Error: The getter 'typeParameters' isn't defined for the class 'InterfaceType'. - 'InterfaceType' is from 'package:analyzer/dart/element/type.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/type.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'typeParameters'.        if (type.typeParameters.length == 2) {                 ^^^^^^^^^^^^^^../../../../../.pub-cache/hosted/pub.dartlang.org/angel_serialize_generator-2.5.0/lib/build_context.dart:68:20: Error: The getter 'type' isn't defined for the class 'ClassElement'. - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.  crawlClass(clazz.type);                   ^^^^../../../../../.pub-cache/hosted/pub.dartlang.org/angel_orm_generator-2.0.5/lib/src/migration_generator.dart:69:56: Error: The getter 'type' isn't defined for the class 'ClassElement'. - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.          .isAssignableFromType(ctx.buildContext.clazz.type);                                                       ^^^^../../../../../.pub-cache/hosted/pub.dartlang.org/angel_orm_generator-2.0.5/lib/src/orm_build_context.dart:28:64: Error: The getter 'type' isn't defined for the class 'ClassElement'. - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.                  .isAssignableFromType(ctx.buildContext.clazz.type));                                                               ^^^^../../../../../.pub-cache/hosted/pub.dartlang.org/angel_orm_generator-2.0.5/lib/src/orm_build_context.dart:262:47: Error: The getter 'typeProvider' isn't defined for the class 'AnalysisContext'. - 'AnalysisContext' is from 'package:analyzer/src/generated/engine.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.1/lib/src/generated/engine.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'typeProvider'.            type = field.type.element.context.typeProvider.intType;                                              ^^^^^^^^^^^^
```

**Comment by kevinelliott** [comment]
```
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "macos_x64"
```

Also fails on 2.10.5 on Linux (destination for deployment).

**Comment by kevinelliott** [comment]
pubspec.lock:

```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  _fe_analyzer_shared:
    dependency: transitive
    description:
      name: _fe_analyzer_shared
      url: "https://pub.dartlang.org"
    source: hosted
    version: "14.0.0"
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.41.1"
  angel_model:
    dependency: transitive
    description:
      name: angel_model
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  angel_orm:
    dependency: "direct main"
    description:
      name: angel_orm
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  angel_orm_generator:
    dependency: "direct dev"
    description:
      name: angel_orm_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  angel_orm_postgres:
    dependency: "direct main"
    description:
      name: angel_orm_postgres
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  angel_serialize:
    dependency: transitive
    description:
      name: angel_serialize
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.3+3"
  angel_serialize_generator:
    dependency: transitive
    description:
      name: angel_serialize_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.5.0"
  args:
    dependency: "direct main"
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.0"
  async:
    dependency: "direct main"
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  buffer:
    dependency: transitive
    description:
      name: buffer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.7"
  build:
    dependency: transitive
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.1"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.5"
  build_daemon:
    dependency: transitive
    description:
      name: build_daemon
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.6"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.2"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.11.0"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.6"
  built_collection:
    dependency: transitive
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.2"
  built_value:
    dependency: transitive
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.1.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  checked_yaml:
    dependency: transitive
    description:
      name: checked_yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  cli_util:
    dependency: transitive
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  code_buffer:
    dependency: transitive
    description:
      name: code_buffer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  code_builder:
    dependency: transitive
    description:
      name: code_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.6.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.13"
  convert:
    dependency: "direct main"
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  coverage:
    dependency: transitive
    description:
      name: coverage
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.2"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  dart_express:
    dependency: "direct main"
    description:
      name: dart_express
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.3"
  dart_style:
    dependency: transitive
    description:
      name: dart_style
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.11"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.2.1"
  fixnum:
    dependency: transitive
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.11"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  googleapis_auth:
    dependency: transitive
    description:
      name: googleapis_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.12+1"
  graphs:
    dependency: transitive
    description:
      name: graphs
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  grpc:
    dependency: "direct main"
    description:
      name: grpc
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.0"
  http:
    dependency: transitive
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.2"
  http2:
    dependency: transitive
    description:
      name: http2
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  http_multi_server:
    dependency: "direct overridden"
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.4"
  inflection2:
    dependency: transitive
    description:
      name: inflection2
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.3"
  intl:
    dependency: transitive
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.8"
  io:
    dependency: transitive
    description:
      name: io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.4"
  jael:
    dependency: transitive
    description:
      name: jael
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  jael_preprocessor:
    dependency: transitive
    description:
      name: jael_preprocessor
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.2"
  json_annotation:
    dependency: "direct main"
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  json_serializable:
    dependency: "direct dev"
    description:
      name: json_serializable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.5.1"
  logging:
    dependency: transitive
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.4"
  markdown:
    dependency: transitive
    description:
      name: markdown
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.8"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.9"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.4"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7"
  mockito:
    dependency: transitive
    description:
      name: mockito
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.1.1"
  mustache4dart:
    dependency: transitive
    description:
      name: mustache4dart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0-dev.1.0"
  nats:
    dependency: "direct main"
    description:
      path: "."
      ref: HEAD
      resolved-ref: f47097525c0e35f5cfeb750ee0326c2e3c13071e
      url: "https://github.com/c16a/nats-dart.git"
    source: git
    version: "0.1.0"
  node_interop:
    dependency: transitive
    description:
      name: node_interop
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.1"
  node_io:
    dependency: transitive
    description:
      name: node_io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  node_preamble:
    dependency: transitive
    description:
      name: node_preamble
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.13"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  path_to_regexp:
    dependency: transitive
    description:
      name: path_to_regexp
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.1"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.2"
  pool:
    dependency: transitive
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  postgres:
    dependency: "direct overridden"
    description:
      name: postgres
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  protobuf:
    dependency: "direct main"
    description:
      name: protobuf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.4"
  pubspec_parse:
    dependency: transitive
    description:
      name: pubspec_parse
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.7"
  quick_log:
    dependency: "direct main"
    description:
      name: quick_log
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.1"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  quiver_hashcode:
    dependency: transitive
    description:
      name: quiver_hashcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  recase:
    dependency: transitive
    description:
      name: recase
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  reflectable:
    dependency: transitive
    description:
      name: reflectable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.9"
  rxdart:
    dependency: transitive
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.25.0"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.9"
  shelf_packages_handler:
    dependency: transitive
    description:
      name: shelf_packages_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  shelf_static:
    dependency: transitive
    description:
      name: shelf_static
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9+1"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3"
  source_gen:
    dependency: transitive
    description:
      name: source_gen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.10+1"
  source_map_stack_trace:
    dependency: transitive
    description:
      name: source_map_stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  source_maps:
    dependency: transitive
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.9"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.6"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  symbol_table:
    dependency: transitive
    description:
      name: symbol_table
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  test:
    dependency: transitive
    description:
      name: test
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.7"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.18+1"
  test_core:
    dependency: transitive
    description:
      name: test_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.11+4"
  timing:
    dependency: transitive
    description:
      name: timing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1+3"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  udp:
    dependency: "direct main"
    description:
      name: udp
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.3"
  vm_service:
    dependency: transitive
    description:
      name: vm_service
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.0"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+15"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  webkit_inspection_protocol:
    dependency: transitive
    description:
      name: webkit_inspection_protocol
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.4"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
sdks:
  dart: ">=2.10.0 <3.0.0"
```

**Comment by kevinelliott** [comment]
`pubspec.yaml`:

```
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  args: ^1.5.2
  angel_orm: ^2.0.2
  angel_orm_postgres: ^1.0.0
  convert:
  json_annotation: ^3.0.1
  nats:
    git: https://github.com/c16a/nats-dart.git
  quick_log: ^0.4.0
  udp: ^3.0.2
  # dart_json_mapper: ^1.5.20
  async: 2.4.0
  grpc: ^2.8.0
  protobuf: ^1.1.0
  dart_express: ^0.5.3
dev_dependencies:
  angel_orm_generator: ^2.0.5
  build_runner:
  json_serializable: ^3.2.5
dependency_overrides:
  http_multi_server: 2.2.0
  postgres: 2.1.1
```
