### ISSUE TITLE
All controllers must carry an @Expose() declaration

### ISSUE THREAD

**Issue by Yonkers** [angel-dart/angel#98]
Just following the [Getting-started](https://angel-dart.gitbook.io/angel/the-basics/installation#getting-started) and I get the following error.

```
Unhandled exception:
Exception: All controllers must carry an @Expose() declaration.
#0      Controller.configureServer (package:angel_framework/src/core/controller.dart:43:7)
#1      Angel.configure.<anonymous closure> (package:angel_framework/src/core/server.dart:328:44)
#2      new Future.sync (dart:async/future.dart:224:31)
#3      Angel.configure (package:angel_framework/src/core/server.dart:328:16)
#4      configureServer (package:test_server_api/src/routes/controllers/controllers.dart:11:13)
<asynchronous suspension>
#5      Angel.configure.<anonymous closure> (package:angel_framework/src/core/server.dart:328:44)
#6      new Future.sync (dart:async/future.dart:224:31)
#7      Angel.configure (package:angel_framework/src/core/server.dart:328:16)
#8      configureServer.<anonymous closure> (package:test_server_api/src/routes/routes.dart:16:15)
<asynchronous suspension>
#9      Angel.configure.<anonymous closure> (package:angel_framework/src/core/server.dart:328:44)
#10     new Future.sync (dart:async/future.dart:224:31)
#11     Angel.configure (package:angel_framework/src/core/server.dart:328:16)
#12     configureServer (package:test_server_api/test_server_api.dart:19:13)
<asynchronous suspension>
#13     Angel.configure.<anonymous closure> (package:angel_framework/src/core/server.dart:328:44)
#14     new Future.sync (dart:async/future.dart:224:31)
#15     Angel.configure (package:angel_framework/src/core/server.dart:328:16)
#16     main.<anonymous closure> (file:///Users/leeo/Develop/work/Projects/test_server_api/bin/dev.dart:12:15)
<asynchronous suspension>
#17     HotReloader._generateServer (package:angel_hot/angel_hot.dart:131:19)
<asynchronous suspension>
#18     HotReloader.startServer (package:angel_hot/angel_hot.dart:140:21)
<asynchronous suspension>
#19     main (file:///Users/leeo/Develop/work/Projects/test_server_api/bin/dev.dart:23:26)
<asynchronous suspension>
#20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

TaskController 
```
import 'package:angel_framework/angel_framework.dart';

@Expose("/task")
class TaskController
    extends Controller
{

  @Expose("/:id")
  Future getTask(id) async {
    return id;
  }

  @Expose("/")
  Future getIndex(ResponseContext res) async {
    await res.render("hello");
  }
}
```

Config:
```
import 'dart:async';
import 'package:angel_framework/angel_framework.dart';
import './task_controller.dart';

Future configureServer(Angel app) async {
  /// Controllers will not function unless wired to the application!
  await app.configure(new TaskController().configureServer);
}
```

pubspec.yaml
```
name: test_server_api
description: An app that's going to be amazing pretty soon.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.0.0-dev <3.0.0'
homepage: https://github.com/angel-dart/angel
dependencies:
  angel_auth: ^2.0.0-alpha # Supports stateless authentication via JWT
  angel_configuration: ^2.0.0 # Loads application configuration, along with support for .env files.
  angel_framework: ^2.0.0-alpha.18 # The core server library.
  angel_jael: ^2.0.0 # Server-side templating engine
  angel_production:  ^1.0.0-alpha.1
  angel_static: ^2.0.0-alpha # Static file server
  angel_validate: ^2.0.0-alpha # Allows for validation of input data
dev_dependencies:
  angel_hot: ^2.0.0 # Hot-reloading support. :)
  angel_test: ^2.0.0-alpha # Utilities for testing Angel servers.
  io: ^0.3.2
  test: ^1.0.0
```
